GEVENT
GEVENT
Detailed Description
Module to build a complete many-to-many event system.
GEVENT provides a simple to use but yet powerful event system.
Precondition
GFX_USE_GEVENT must be set to TRUE in your gfxconf.h
Functions
void geventListenerInit (GListener *pl)
Create a Listener.
bool_t geventAttachSource (GListener *pl, GSourceHandle gsh, uint32_t flags)
Attach a source to a listener.
void geventDetachSource (GListener *pl, GSourceHandle gsh)
Detach a source from a listener.
GEvent * geventEventWait (GListener *pl, delaytime_t timeout)
Wait for an event on a listener from an assigned source.
void geventEventComplete (GListener *pl)
Release the GEvent buffer associated with a listener.
GSourceListener * geventGetSourceListener (GSourceHandle gsh, GSourceListener *lastlr)
Called by a source with a possible event to get a listener record.
GEvent * geventGetEventBuffer (GSourceListener *psl)
Get the event buffer from the GSourceListener.
void geventSendEvent (GSourceListener *psl)
Called by a source to indicate the listener's event buffer has been filled.
void geventDetachSourceListeners (GSourceHandle gsh)
Detach any listener that has this source attached.
GEVENT Functionality to be included
#define GEVENT_ASSERT_NO_RESOURCE FALSE
Should routines assert() if they run out of resources.
GEVENT Optional Sizing Parameters
#define GEVENT_MAXIMUM_SIZE 32
Defines the maximum size of an event status variable.
#define GEVENT_MAX_SOURCE_LISTENERS 32
Defines the maximum Source/Listener pairs in the system.
Function Documentation
bool_t geventAttachSource (GListener * pl, GSourceHandle gsh, uint32_t flags)
Attach a source to a listener.
Flags are interpreted by the source when generating events for each listener. If this source is already assigned to the listener it will update the flags. If insufficient resources are available it will either assert or return FALSE depending on the value of GEVENT_ASSERT_NO_RESOURCE.
Parameters
[in] pl The listener
[in] gsh The source which has to be attached to the listener
[in] flags The flags
Returns
TRUE if succeeded, FALSE otherwise
Definition at line 74 of file gevent.c.
References FALSE, GEVENT_MAX_SOURCE_LISTENERS, gfxMutexEnter(), gfxMutexExit(), and TRUE.
void geventDetachSource (GListener * pl, GSourceHandle gsh)
Detach a source from a listener.
If gsh is NULL detach all sources from this listener and if there is still a thread waiting for events on this listener, it is sent the exit event.
Parameters
[in] pl The listener
[in] gsh The source
Definition at line 111 of file gevent.c.
References gfxMutexEnter(), and gfxMutexExit().
void geventDetachSourceListeners (GSourceHandle gsh)
Detach any listener that has this source attached.
Parameters
[in] gsh The source handle
Definition at line 232 of file gevent.c.
References gfxMutexEnter(), and gfxMutexExit().
void geventEventComplete (GListener * pl)
Release the GEvent buffer associated with a listener.
The GEvent returned by geventEventWait() is released.
Note
The GEvent pointer returned by geventEventWait() is released when geventEventWait() is called again or when this function is called. The GEvent object MUST NOT be used after this function is called.
Parameters
[in] pl The listener
Definition at line 152 of file gevent.c.
References gfxMutexEnter(), and gfxMutexExit().
GEvent* geventEventWait (GListener * pl, delaytime_t timeout)
Wait for an event on a listener from an assigned source.
The type of the event should be checked (pevent->type) and then pevent should be typecast to the actual event type if it needs to be processed. timeout specifies the time to wait in system ticks. TIME_INFINITE means no timeout - wait forever for an event. TIME_IMMEDIATE means return immediately
Note
The returned GEvent is released when this routine is called again or when optionally geventEventComplete() is called. Calling geventEventComplete() allows the GEvent object to be reused earlier which can reduce missed events. The GEvent object MUST NOT be used after this function is called (and is blocked waiting for the next event) or after geventEventComplete() is called.
Parameters
[in] pl The listener
[in] timeout The timeout
Returns
NULL on timeout
Definition at line 121 of file gevent.c.
References gfxMutexEnter(), gfxMutexExit(), and gfxSemWait().
GEvent* geventGetEventBuffer (GSourceListener * psl)
Get the event buffer from the GSourceListener.
A NULL return allows the source to record (perhaps in glr->scrflags) that the listener has missed events. This can then be notified as part of the next event for the listener. The buffer can only be accessed untill the next call to geventGetSourceListener or geventSendEvent
Parameters
[in] psl The source listener
Returns
NULL if the listener is not currently listening.
Definition at line 192 of file gevent.c.
References gfxMutexEnter(), and gfxMutexExit().
GSourceListener* geventGetSourceListener (GSourceHandle gsh, GSourceListener * lastlr)
Called by a source with a possible event to get a listener record.
lastlr should be NULL on the first call and thereafter the result of the previous call.
Parameters
[in] gsh The source handler
[in] lastlr The source listener
Returns
NULL when there are no more listeners for this source
Definition at line 168 of file gevent.c.
References GEVENT_MAX_SOURCE_LISTENERS, gfxMutexEnter(), and gfxMutexExit().
void geventListenerInit (GListener * pl)
Create a Listener.
If insufficient resources are available it will either assert or return NULL depending on the value of GEVENT_ASSERT_NO_RESOURCE.
Parameters
[in] pl A listener
Definition at line 67 of file gevent.c.
References gfxSemInit().
void geventSendEvent (GSourceListener * psl)
Called by a source to indicate the listener's event buffer has been filled.
After calling this function the source must not reference in fields in the GSourceListener or the event buffer.
Parameters
[in] psl The source listener
Definition at line 206 of file gevent.c.
References gfxMutexEnter(), gfxMutexExit(), and gfxSemSignal().
Macro Definition Documentation
#define GEVENT_ASSERT_NO_RESOURCE FALSE
Should routines assert() if they run out of resources.
Defaults to FALSE.
If FALSE the application must be prepared to handle these failures.
Definition at line 30 of file gevent_options.h.
#define GEVENT_MAX_SOURCE_LISTENERS 32
Defines the maximum Source/Listener pairs in the system.
Defaults to 32
Definition at line 50 of file gevent_options.h.
Referenced by geventAttachSource(), and geventGetSourceListener().
#define GEVENT_MAXIMUM_SIZE 32
Defines the maximum size of an event status variable.
Defaults to 32 bytes
Definition at line 43 of file gevent_options.h.