Renderings
Renderings
GWIN » Widgets » Progressbar
Detailed Description
Built-in rendering functions for the progressbar widget.
These function may be passed to gwinSetCustomDraw() to get different progressbar drawing styles.
Note
In your custom progressbar drawing function you may optionally call these standard functions and then draw your extra details on top.
These custom drawing routines don't have to worry about setting clipping as the framework sets clipping to the object window prior to calling these routines.
Functions
void gwinProgressbarDraw_Std (GWidgetObject *gw, void *param)
The default rendering function for the progressbar widget.
void gwinProgressbarDraw_Image (GWidgetObject *gw, void *param)
Renders a progressbar using an image.
Function Documentation
void gwinProgressbarDraw_Image (GWidgetObject * gw, void * param)
Renders a progressbar using an image.
Parameters
[in] gw The widget object (must be a progressbar handle)
[in] param A parameter passed in from the user. Must be an image handle. See note below.
Note
The image must be already opened before calling gwinSetCustomDraw().
The image is tiled to fill the active area of the progressbar. The normal colors apply to the border and inactive area and the dividing line between the active and inactive areas. No checking is done to compare the dimensions of the progressbar to the size of the image. Note text is drawn on top of the image.
Precondition
GDISP_NEED_IMAGE must be set to TRUE
Function Class:
Normal API, this function can be invoked by regular system threads.
Referenced by gwinProgressbarDraw_Std().
void gwinProgressbarDraw_Std (GWidgetObject * gw, void * param)
The default rendering function for the progressbar widget.
Parameters
[in] gw The widget object (must be a progressbar object)
[in] param A parameter passed in from the user. Ignored by this function.
Function Class:
Normal API, this function can be invoked by regular system threads.
Definition at line 230 of file gwin_progressbar.c.
References GWidgetStyle::disabled, GWindowObject::display, GColorSet::edge, GWidgetStyle::enabled, GColorSet::fill, GWindowObject::flags, GWidgetObject::g, gdispGDrawBox(), gdispGDrawLine(), gdispGDrawStringBox(), gdispGFillArea(), gdispGImageDraw(), gwinProgressbarDraw_Image(), GWindowObject::height, justifyCenter, GColorSet::progress, GWidgetObject::pstyle, GColorSet::text, GWidgetObject::text, GWindowObject::vmt, GWindowObject::width, GWindowObject::x, and GWindowObject::y.