Renderings
Renderings
GWIN » Widgets » Checkbox
Detailed Description
Built-in rendering functions for the checkbox widget.
These function may be passed to gwinSetCustomDraw() to get different checkbox drawing styles.
Note
In your custom checkbox drawing function you may optionally call these standard functions and then draw your extra details on top.
These custom drawing routines don't have to worry about setting clipping as the framework sets clipping to the object window prior to calling these routines.
Functions
void gwinCheckboxDraw_CheckOnLeft (GWidgetObject *gw, void *param)
Renders a square checkbox where the text is on the right side of the checkbox.
void gwinCheckboxDraw_CheckOnRight (GWidgetObject *gw, void *param)
Renders a square checkbox where the text is on the left side of the checkbox.
void gwinCheckboxDraw_Button (GWidgetObject *gw, void *param)
Renders a checkbox in form of a rectangular button with the text inside of it.
Function Documentation
void gwinCheckboxDraw_Button (GWidgetObject * gw, void * param)
Renders a checkbox in form of a rectangular button with the text inside of it.
This behaves like a button that can be toggled.
Parameters
[in] gw The widget (must be a checkbox)
[in] param A parameter passed in from the user. Ignored by this function.
Function Class:
Normal API, this function can be invoked by regular system threads.
Definition at line 254 of file gwin_checkbox.c.
References GWindowObject::display, GColorSet::edge, GColorSet::fill, FIXED, GWidgetObject::g, gdispBlendColor(), gdispGDrawLine(), gdispGDrawStringBox(), GWindowObject::height, justifyCenter, GColorSet::text, GWidgetObject::text, TRUE, GWindowObject::vmt, GWindowObject::width, GWindowObject::x, and GWindowObject::y.
Referenced by gwinCheckboxDraw_CheckOnRight().
void gwinCheckboxDraw_CheckOnLeft (GWidgetObject * gw, void * param)
Renders a square checkbox where the text is on the right side of the checkbox.
Parameters
[in] gw The widget (must be a checkbox)
[in] param A parameter passed in from the user. Ignored by this function.
Function Class:
Normal API, this function can be invoked by regular system threads.
Definition at line 175 of file gwin_checkbox.c.
References GWidgetStyle::background, GWindowObject::display, GColorSet::edge, GColorSet::fill, GWindowObject::flags, GWidgetObject::g, GCHECKBOX_FLG_CHECKED, gdispGDrawBox(), gdispGFillArea(), gdispGFillStringBox(), GWindowObject::height, justifyLeft, GWidgetObject::pstyle, GColorSet::text, GWidgetObject::text, GWindowObject::vmt, GWindowObject::width, GWindowObject::x, and GWindowObject::y.
void gwinCheckboxDraw_CheckOnRight (GWidgetObject * gw, void * param)
Renders a square checkbox where the text is on the left side of the checkbox.
Parameters
[in] gw The widget (must be a checkbox)
[in] param A parameter passed in from the user. Ignored by this function.
Function Class:
Normal API, this function can be invoked by regular system threads.
Definition at line 204 of file gwin_checkbox.c.
References GWidgetStyle::background, GWindowObject::display, GColorSet::edge, GColorSet::fill, GWindowObject::flags, GWidgetObject::g, GCHECKBOX_FLG_CHECKED, gdispGDrawBox(), gdispGDrawLine(), gdispGFillArea(), gdispGFillStringBox(), gwinCheckboxDraw_Button(), GWindowObject::height, justifyCenter, justifyRight, GWidgetObject::pstyle, GColorSet::text, GWidgetObject::text, TRUE, GWindowObject::vmt, GWindowObject::width, GWindowObject::x, and GWindowObject::y.