./file2c -c -n splash -f splash.bmp splash.bmp ../romfs/romfs_splash.h
./file2c -c -n en00 -f en00.bmp en00.bmp ../romfs/romfs_en00.h
./file2c -c -n en01 -f en01.bmp en01.bmp ../romfs/romfs_en01.h
./file2c -c -n en10 -f en10.bmp en10.bmp ../romfs/romfs_en10.h
./file2c -c -n en11 -f en11.bmp en11.bmp ../romfs/romfs_en11.h
./file2c -c -n en20 -f en20.bmp en20.bmp ../romfs/romfs_en20.h
./file2c -c -n en21 -f en21.bmp en21.bmp ../romfs/romfs_en21.h
./file2c -c -n ufo -f ufo.bmp ufo.bmp ../romfs/romfs_ufo.h
./file2c -c -n exp -f exp.bmp exp.bmp ../romfs/romfs_exp.h
./file2c -c -n player -f player.bmp player.bmp ../romfs/romfs_player.h
